name: Build .deb Package for prometheus-postgres-exporter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-buster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image for Debian buster
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg DEBIAN_VERSION=buster \
            -t prometheus-postgres-exporter:buster \
            .

  build-bullseye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image for Debian bullseye
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg DEBIAN_VERSION=bullseye \
            -t prometheus-postgres-exporter:bullseye \
            .

  build-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image for Debian bookworm
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg DEBIAN_VERSION=bookworm \
            -t prometheus-postgres-exporter:bookworm \
            .
