name: Build .deb Package for prometheus-postgres-exporter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-buster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image and create .deb for Debian buster
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg DEBIAN_VERSION=buster \
            -t prometheus-postgres-exporter:buster \
            .
          docker run --rm -v ${{ github.workspace }}/deb_build:/workspace/deb_build prometheus-postgres-exporter:buster

      - name: Upload .deb Artifact for buster
        uses: actions/upload-artifact@v3
        with:
          name: prometheus-postgres-exporter-buster.deb
          path: deb_build/prometheus-postgres-exporter.deb

  build-bullseye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image and create .deb for Debian bullseye
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg DEBIAN_VERSION=bullseye \
            -t prometheus-postgres-exporter:bullseye \
            .
          docker run --rm -v ${{ github.workspace }}/deb_build:/workspace/deb_build prometheus-postgres-exporter:bullseye

      - name: Upload .deb Artifact for bullseye
        uses: actions/upload-artifact@v3
        with:
          name: prometheus-postgres-exporter-bullseye.deb
          path: deb_build/prometheus-postgres-exporter.deb

  build-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image and create .deb for Debian bookworm
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg DEBIAN_VERSION=bookworm \
            -t prometheus-postgres-exporter:bookworm \
            .
          docker run --rm -v ${{ github.workspace }}/deb_build:/workspace/deb_build prometheus-postgres-exporter:bookworm

      - name: Upload .deb Artifact for bookworm
        uses: actions/upload-artifact@v3
        with:
          name: prometheus-postgres-exporter-bookworm.deb
          path: deb_build/prometheus-postgres-exporter.deb

          