name: Build .deb Package for prometheus-postgres-exporter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_version: [buster, bullseye, bookworm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image and create .deb package for ${{ matrix.debian_version }}
        run: |
          # Ensure the deb_build directory exists in the runner
          mkdir -p deb_build
          # Build and run the Docker container
          docker build \
            --file docker/Dockerfile \
            --build-arg DEBIAN_VERSION=${{ matrix.debian_version }} \
            -t prometheus-postgres-exporter:${{ matrix.debian_version }} \
            .
          docker run --rm \
            -v ${{ github.workspace }}/deb_build:/workspace/deb_build \
            prometheus-postgres-exporter:${{ matrix.debian_version }}

      - name: Check deb_build directory contents
        run: ls -R deb_build # Confirm the .deb file is in this directory

      - name: Upload .deb Artifact for ${{ matrix.debian_version }}
        uses: actions/upload-artifact@v3
        with:
          name: prometheus-postgres-exporter-${{ matrix.debian_version }}.deb
          path: deb_build/prometheus-postgres-exporter.deb
